name: SSH Access to VM

on: [push]  # Trigger the workflow on push events (you can adjust this)

jobs:
  ssh-access:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-hamza@172.30.205.125
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Connect to VM and Run Commands
      run: |
        ssh -o StrictHostKeyChecking=no hamza@172.30.205.125 'bash -s' << 'EOF'
        # Replace this line with your commands to be executed on the VM
        echo "Connected to VM successfully"
        EOF
