name: Setup Sniffer with VPN

on:
  workflow_dispatch:

jobs:
  setup-sniffer-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OpenVPN and SSH client
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn openssh-client sshpass

    - name: Add VPN configuration
      run: |
        mkdir -p ~/vpn
        echo "${{ secrets.OVPN_FILE }}" > ~/vpn/client.ovpn

    - name: Start VPN connection
      run: |
        sudo openvpn --config ~/vpn/client.ovpn --daemon
        sleep 30 # Give some time for VPN to establish connection

    - name: Check OpenVPN logs
      run: |
        cat /var/log/syslog | grep openvpn

    - name: Verify VPN connection
      run: |
        ifconfig # Check if VPN interface is up
        ping -c 4 vm-client-ip # Replace with the actual IP you want to test

    - name: SSH and setup sniffer on client
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "$SSH_PASSWORD" | sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no user@vm-client-ip 'bash -s' <<'EOF'
        # Commands to set up the sniffer in client mode
        echo "Setting up sniffer in client mode"
        EOF

  setup-sniffer-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install OpenVPN and SSH client
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn openssh-client sshpass

    - name: Add VPN configuration
      run: |
        mkdir -p ~/vpn
        echo "${{ secrets.OVPN_FILE }}" > ~/vpn/client.ovpn

    - name: Start VPN connection
      run: |
        sudo openvpn --config ~/vpn/client.ovpn --daemon
        sleep 30 # Give some time for VPN to establish connection

    - name: Check OpenVPN logs
      run: |
        cat /var/log/syslog | grep openvpn

    - name: Verify VPN connection
      run: |
        ifconfig # Check if VPN interface is up
        ping -c 4 vm-server-ip # Replace with the actual IP you want to test

    - name: SSH and setup sniffer on server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "$SSH_PASSWORD" | sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no user@vm-server-ip 'bash -s' <<'EOF'
        # Commands to set up the sniffer in server mode
        echo "Setting up sniffer in server mode"
        EOF
