name: Setup Sniffer

on:
  workflow_dispatch:

jobs:
  setup-sniffer-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: SSH and setup sniffer on client
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "$SSH_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no user@vm-client-ip 'bash -s' <<'EOF'
        # Commands to set up the sniffer in client mode
        # Replace the following line with your setup commands
        echo "Setting up sniffer in client mode"
        EOF

  setup-sniffer-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: SSH and setup sniffer on server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "$SSH_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no user@vm-server-ip 'bash -s' <<'EOF'
        # Commands to set up the sniffer in server mode
        # Replace the following line with your setup commands
        echo "Setting up sniffer in server mode"
        EOF
